services:
  playnode:
    image: "public.ecr.aws/j7l3n4i5/client/flask-app-${ENV:-prod}:latest"
    container_name: playnode
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - FLASK_APP=app.py
      - TORCHSERVE_PORT=8083
      - HOST_NAME=torchserve
    depends_on:
      - torchserve

  torchserve:
    image: "public.ecr.aws/j7l3n4i5/playai-node-ai-engine-public-${ENV:-prod}:inference-latest"
    container_name: torchserve
    environment:
      - TORCHSERVE_PORT=8083
    ports:
      - "8083:8083"          # Bind the inference port
      - "8084:8084"          # Bind the management port


  postprocessing:
      image: "public.ecr.aws/j7l3n4i5/playai-node-ai-engine-public-${ENV:-prod}:postprocessing-latest"
      container_name: postprocessing
      command:
        - "postprocess_lambda_function.lambda_handler"
      ports:
        - "8080:8080"
